AWSTemplateFormatVersion: 2010-09-09
Description: EC2 CREATION TEMPLATE EXAMPLE

Resources: 
  DevEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      #Get it from the console every region has a different id
      ImageId: ami-0a243dbef00e96192
      InstanceType: t2.micro 
      KeyName: cfn-key-2