AWSTemplateFormatVersion: 2010-09-09
Description: a detailed ec2 stack for training  

Parameters:
  MySSHKeyName:
    Description: Select a key name from the list
    Type: AWS::EC2::KeyPair::KeyName


Resources:

  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref MySSHKeyName
      ImageId: ami-0a243dbef00e96192
      InstanceType: t2.micro
      SecurityGroups: 
        - !Ref SSHSecurityGroup #a function that refers to that resource or a parameter value
      Tags:
        - Key: Name
          Value: cloudformation-training-instance
  
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:  security group allow ssh port only
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 #all the internet
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

  MyElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DevEC2Instance
